apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap

data:
  MONGO_HOST: mongo-service-clusterip
  MONGO_PORT: "27017"
  MONGO_DATABASE: Kubernetes
  REDIS_HOST: redis-service-clusterip
  REDIS_PORT: "6379"
  API_PORT: "5000"
  SERVER_IP: server-service-clusterip